### ISSUE TITLE
Compilation error on Rust Nightly.

### ISSUE THREAD

**Issue by q2p** [rust-rocksdb/rust-rocksdb#557]
Previously the binary was compiling successfully. But after updating some dependencies, the compilation error started to pop up.

The error is:

```
...

warning: Linking globals named 'bz_internal_error': symbol multiply defined!

error: failed to load bc of "librocksdb_sys-9d949a5fee4910bc.librocksdb_sys.850941a7-cgu.0.rcgu.o": 

warning: `monolith` (bin "monolith") generated 12 warnings
error: could not compile `monolith` due to previous error; 12 warnings emitted
```

The packages `librocksdb-sys v6.20.3` and `rocksdb v0.17.0` themselves compiled successfully. The error occurs only during the final compilation of the binary.

I've tried toggling different compilation options and compiling both with `dev` and `release` profiles, the error message does not change.

Googling the error message also didn't reveal anything helpful, so I'm kind of lost.

<details>
<summary>Contents of ./Cargo.toml inside of a workspace directory ...</summary>

```toml
[build]
jobs = 1

[profile.test]
opt-level = 0
debug = true
rpath = true
debug-assertions = true
lto = "off"
codegen-units = 256
panic = "unwind"
incremental = true
overflow-checks = true

[profile.dev]
opt-level = 0
debug = true
rpath = true
debug-assertions = true
lto = "off"
codegen-units = 256
panic = "unwind"
incremental = true
overflow-checks = true

[profile.release]
opt-level = 3
debug = false
rpath = false
debug-assertions = false
lto = "fat"
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = false

[profile.release.package."*"]
opt-level = 3
debug = false
codegen-units = 1
incremental = false
overflow-checks = false

[workspace]
members = [
	"derive_getters",
	"utils",
	"storage_abstraction",
	"b_heap",
	"http_parser",
	"html_parser",
	"monolith",
]
```

</details>

<details>
<summary>Contents of ./monolith/Cargo.toml inside of the binary directory ...</summary>

```toml
[package]
name = "monolith"
version = "0.0.1"
edition = "2018"
publish = false
build = "src/build.rs"

[build]
jobs = 1

[dependencies]
utils = { path = "../utils" }
derive_getters = { path = "../derive_getters" }
storage_abstraction = { path = "../storage_abstraction" }
http_parser = { path = "../http_parser" }
html_parser = { path = "../html_parser" }
b_heap = { path = "../b_heap" }

rand = { version = "0.8.4", features = ["small_rng"] }
ring = "0.16.20"
mio = { version = "0.7.13", features = ["tcp", "os-poll"] }
slab = "0.4.4"

webpki-roots = "0.22.0"
webpki = "0.22.0"
rustls = "0.20.0"

blake2-rfc = "0.2.18"

twox-hash = "1.6.1"
siphasher = "0.3.7"

serde = { version = "1.0.130", features = ["derive"] }
serde_derive = "1.0.130"
serde_json = "1.0.68"
chrono = "0.4.19"
panoradix = "0.6.6"
num-traits = "0.2.14"
lazy_static = "1.4.0"

tempfile = "3.2.0"

sorted-vec = "0.5.2"
arrayvec = "0.7.1"

generic-array = "0.14.4"

rocksdb = "0.17.0"

bincode = "1.3.1"

flate2 = { version = "1.0.22", features = ["zlib-ng-compat"], default-features = false }
brotli = "3.3.0"

urlencoding = "2.0.0"

ctrlc = { version = "3.2.0", features = ["termination"] }

zip = "0.5"
encoding_rs = "0.8.28"
crc32fast = "1.2.1"

[build-dependencies]
html_parser = { path = "../html_parser" }

[dev-dependencies]
rand_pcg = "0.3.0"
tempfile = "3.2.0"
```

</details>
